name: Create Release

on:
  push:
    tags:
      - 'v*' # Only trigger on tags starting with 'v'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is a test release. # Fixed extra spaces
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./dist
