name: Create Release

on:
  push:
    tags:
      - 'v*' # Only trigger on tags starting with 'v'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate new unique tag
        run: |
          NEW_TAG="v$(date +'%Y%m%d%H%M%S')" # Generates a tag like 'v20231204084530'
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body: |
            This is a test release.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
